version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ninnemana/direct-store
    docker:
      - image: circleci/golang:1.8
    steps:
      - run: cd /go/src/github.com/ninnemana/direct-store
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run: cd /go/src/github.com/ninnemana/direct-store
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go test -v ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test