version: 2
jobs:
  build:
    docker:
        - image: golang:1.8
    working_directory: /go/src/github.com/ninnemana/direct-store
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/...
      - run: dep ensure
      - run: go install
      - run: go test -race -cover $(go list ./... | grep -v /vendor/)